import Head from 'next/head';
import { TypewriterClass } from 'typewriter-effect';
import Image from 'next/image'
import MyPhoto from 'file:///C:/Users/Tom/Desktop/Game.png';
import MyPhoto2 from 'file:///C:/Users/Tom/Desktop/Game2.png';
import MyPhoto3 from 'file:///C:/Users/Tom/Desktop/Game3.png';
import Link from "next/link";


export default function Game(){
    return(
      <div>
        <Head>
          <meta name="description" content="Generated by create next app" />
        </Head>
     
        <main className='min-h-screenr'>
        <div className='flex h-150 items-center justify-center'>
          
          <div class="p-2">
                  <Image src={MyPhoto2} class="shadow-lg rounded max-w-full h-auto align-middle border-none object-cover h-1279 w-96" />  
          </div>
          <div class="p-2">
                  <Image src={MyPhoto} class="shadow-lg rounded max-w-full h-auto align-middle border-none object-cover h-1279 w-96" />  
          </div>
          <div class="p-2">
                  <Image src={MyPhoto3} class="shadow-lg rounded max-w-full h-auto align-middle border-none object-cover h-1279 w-96" />  
          </div>
          
        </div>
        <div className='flex items-center justify-center '>
        <div className='text-7xl text-center text-white'>2D Game Development</div>
        </div>
        <div className='flex items-center justify-evenly '>
        <div className='text-sm text-center text-white p-10'>For this assignment, the task was to “develop a prototype video game using the Unity Engine.” The game should be developed in 2D and be playable by only a single player. This essay will consider the overall games visuals, audio and interactivity and will cover its functionality towards benefiting the player while highlighting the challenges behind the coding itself. The functionality of the game is truly based down to the coding and the visuals give the players the attraction to the game, mixing them well while applying simple and interactive audio, an interesting and simple game can be made.</div>
        </div>
        <div className='flex items-center justify-center '>
          <Link href='/Projects'><button class="mt-2 rounded-lg bg-Pink py-1 px-2 text-m hover:bg-Pink">Back Page</button></Link> 
        </div>
        </main>
      </div>

)
}