import Head from 'next/head';
import { TypewriterClass } from 'typewriter-effect';
import Image from 'next/image'
import MyPhoto from 'file:///C:/Users/Tom/Desktop/Game.png';
import MyPhoto2 from 'file:///C:/Users/Tom/Desktop/code.png';
import Link from "next/link";


export default function Contacts(){
    return(
      <div>
      <Head>
      <meta name="description" content="Generated by create next app" />
      </Head>
     <main className='min-h-screenr'>
      
     </main>
      </div>

)
}