import Head from 'next/head';
import { TypewriterClass } from 'typewriter-effect';
import Image from 'next/image'
import MyPhoto from 'file:///C:/Users/Tom/Desktop/Game.png';
import Link from "next/link";

export default function Esports(){
    return(
      <div>
        <Head>
          <meta name="description" content="Generated by create next app" />
        </Head>
     
        <main className='min-h-screenr'>
        <div className='flex h-screen items-center justify-center'>
        <Link href='/Projects'><button class="mt-2 rounded-lg bg-neutral-800 py-1 px-2 text-m hover:bg-neutral-900">Read More</button>
        </Link>
            </div>  
        </main>
      </div>

)
}