import Head from 'next/head';
import { TypewriterClass } from 'typewriter-effect';
import Image from 'next/image'
import MyPhoto from "../../public/Images/EastL.jpg";
import MyPhoto2 from "../../public/Images/htmlblack.png";
import MyPhoto3 from "../../public/Images/cssblack.png";
import MyPhoto4 from "../../public/Images/js.png";
import MyPhoto5 from "../../public/Images/mysql.png";
import MyPhoto6 from "../../public/Images/csharp.png";




export default function About(){
    return(
      <div>
        <Head>
          <meta name="description" content="Generated by create next app" />
        </Head>
     
        <main className='min-h-screenr' >
        <div className=''>
          <div className='flex h-32 items-center justify-evenly p-10 bg-opacity-10 shadow-lg rounded '>
              <div class="text-7xl text-white font-bold p-10 sm:text-5xl sm:w-auto">
                <p>About Me</p>
                <div className='text-xl w-150 sm:w-auto'>Im currently studying at Eastleigh College doing a btec in Computer sceince.</div>
              </div>
              <div class="p-10 sm:hidden">
                <Image src={MyPhoto} class="shadow-lg rounded max-w-full h-auto align-middle border-none object-cover h-1279 w-96" /> 
              </div>
          </div>
          <div className='flex h-30 items-center justify-evenly p-10 bg-opacity-10 shadow-lg rounded '> 
              <div class="p-10 sm:hidden">
                <Image src={MyPhoto2} class="shadow-lg rounded max-w-full h-auto align-middle border-none object-cover h-1279 w-96" /> 
              </div>
              <div class="text-7xl text-white font-bold p-10 sm:text-5xl sm:w-auto">
                <p>HTML</p>
                <div className='text-xl w-150 sm:w-auto'>Having done HTML for a mojority of college projects i love building and devloping websites as i have a love for design.</div>
              </div>     
        </div>
        <div className='flex h-30 items-center justify-evenly p-10 bg-opacity-10 shadow-lg rounded '> 
              
              <div class="text-7xl text-white font-bold p-10 sm:text-5xl sm:w-auto ">
                <p>CSS</p>
                <div className='text-xl w-150 sm:w-auto'>With css being a staple for designing websites, understanding it in all its formats is a great pleasure. Using Tailwind specifically for this wesbite, it has given me more of a chance to develop my coding skills and its greatness.</div>
              </div> 
              <div class="p-10 sm:hidden">
                <Image src={MyPhoto3} class="shadow-lg rounded max-w-full h-auto align-middle border-none object-cover h-1279 w-96" /> 
              </div> 

        </div>  
        <div className='flex h-30 items-center justify-evenly p-10 bg-opacity-10 shadow-lg rounded '> 
              <div class="p-10 sm:hidden">
                <Image src={MyPhoto4} class="shadow-lg rounded max-w-full h-auto align-middle border-none object-cover h-1279 w-96" /> 
              </div>
              <div class="text-7xl text-white font-bold p-10 sm:text-5xl sm:w-auto">
                <p>JavaScript</p>
                <div className='text-xl w-150 sm:w-auto'>Java script being the pinicale of near to all projects in college and the first subject of focus, my every growing knowledge on it is very large.</div>
              </div>     
        </div>
        <div className='flex h-30 items-center justify-evenly p-10 bg-opacity-10 shadow-lg rounded '> 
              
              <div class="text-7xl text-white font-bold p-10 sm:text-5xl sm:w-auto">
                <p>MySQL</p>
                <div className='text-xl w-150 sm:w-auto'>Using MySql for an Esports website, having a small but greater than basic understanding. the knowledge of Structured Query Language means im happy to work with it and improve my skill in it.</div>
              </div> 
              <div class="p-10 sm:hidden">
                <Image src={MyPhoto5} class="shadow-lg rounded max-w-full h-auto align-middle border-none object-cover h-1279 w-96" /> 
              </div> 

        </div>

        <div className='flex h-30 items-center justify-evenly p-10 bg-opacity-10 shadow-lg rounded '> 
              <div class="p-10 sm:hidden">
                <Image src={MyPhoto6} class="shadow-lg rounded max-w-full h-auto align-middle border-none object-cover h-1279 w-96" /> 
              </div>
              <div class="text-7xl text-white font-bold p-10 sm:text-5xl sm:w-auto">
                <p>C#</p>
                <div className='text-xl w-150 sm:w-auto'>Using C# for creating a 2D asteroids game, i found great joy when using it and getting to grips with it. </div>
              </div>     
        </div>
        </div>
        </main>
      </div>

)
}