
import Head from 'next/head';


export default function Home(){
  return(
    <div>
    <Head>
    <meta name="description" content="Generated by create next app" />
    </Head>
   <main className='flex items-center min-h-screenr bg-dark'>

   </main>
    </div>
    
  )
}
