
import Head from 'next/head';
import { TypewriterClass } from 'typewriter-effect';
import Image from 'next/image'
import Link from "next/link";
import MyPhoto from "../../public/Images/PicOfMe.jpeg";
import TextAnimation from '../../components/TextAnimation';


export default function Home(){
  return(
    <div>
    <Head>
      <meta name="description" content="Generated by create next app" />
    </Head>
    <main className='max-h-screenr sm:bg-black'>
      <div className='flex h-screen items-center justify-evenly sm:grid grid-cols-1'>
        <div class="flex items-center justify-evenly p-1 sm:mt-32">
          <Image src={MyPhoto} class="flex image-center shadow-lg rounded h-1279 w-96 :h-1279 sm:w-64 sm:image-center" /> 
        </div> 
        <div className=' p-2 rounded-lg bg-opacity-10 shadow-lg rounded sm:mb-32'>
          <TextAnimation className='text-7xl text-white font-bold sm:text-5xl' text="Hi I'm Tom" />
          <TextAnimation className='text-4xl text-center sm:text-2xl' text="Im a junior software developer currently in college." />
        </div>
      </div>
      
      
      
      
        
      


        
    </main>
    </div>
    
  )
}
